= Teiid Sizing Application

Teiid Sizing Application contains a series of tools/utils that provides sizing, profiling recommendations for runing http://teiid.jboss.org/[Teiid Server] or http://www.jboss.org/products/datavirt/overview/[Red Hat JBoss Data Virtualization].

Features:

* Serializing/Deserializing linear regression rate caculation

== Build

* Install JDK 1.7 or higher
* Install maven 3
* Create a github account and fork Project

Enter the following:

----
$ git clone https://github.com/<yourname>/teiid-sizing-application.git
$ cd teiid-sizing-application
$ mvn clean install -P release
----

you will find distribution `teiid-sizing-jar.jar` under "build/target" directory once the build is completed.


== Run

[cols="5a,2,2"]
|===
|Utils |Description |Notes

|
[source,java]
----
java -jar teiid-sizing-jar.jar deserialization <size> <counts>
----
|A tool is used to calculate deserializing linear regression rate between size and time. <size> - total size in MB to be deserialized, a integer, eg, 100, 200, etc. <counts> - total number of tuples(size, time) to be collected, a integer which should be equals 1 << X, eg, 128, 256, 512, 1024, 2048, etc
|deserialization will run several minutes if parameter size setting is large.
|===
